In [1]:
%matplotlib notebook
%gui qt
import numpy as np
from numpy import pi
from vertex_model_2d_sphere import VertexModelSphere

In [2]:
from voronoi_cells import random_voronoi_cells_sphere

In [3]:
locs,adjs = random_voronoi_cells_sphere(4,1)

[array([ 0.11745741,  0.26185631,  0.95793269]), array([-0.23275304,  0.06069538,  0.97064004]), array([-0.03221946, -0.0041768 ,  0.99947209]), array([ 0.0524311 , -0.08721151,  0.99480909]), array([ 0.76781384,  0.56146281,  0.30857969]), array([-0.21964567,  0.9734936 ,  0.06376512]), array([-0.98276713, -0.02969906,  0.1824465 ]), array([ 0.08208419, -0.96929702,  0.23178757]), array([ 0.66909232,  0.2617162 , -0.69557178]), array([-0.42007667,  0.73797596, -0.52813547]), array([-0.52670496, -0.55062864, -0.64760326]), array([ 0.51656148, -0.66945202, -0.53385226]), array([ 0.14588977,  0.11192535, -0.98294908]), array([-0.03023158,  0.12470037, -0.99173377]), array([-0.10982095, -0.57747645, -0.80898722]), array([ 0.64051894, -0.18475334, -0.74538694])]
<scipy.spatial._spherical_voronoi.SphericalVoronoi instance at 0x122558b90>
[[5, 14, 15, 7, 6], [13, 14, 15, 18, 17, 16], [7, 15, 18], [1, 17, 18, 7, 6], [1, 6, 5, 11, 10, 9, 8], [2, 12, 11, 5, 14, 13], [0, 3, 2, 13, 16], [0, 21, 2

In [4]:
vms = VertexModelSphere(locs,adjs)

In [8]:
vms.draw_model()

In [14]:
def relax_a_bunch_of_vms(n_vms):
    for i in range(n_vms):
        locs,adjs = random_voronoi_cells_sphere(4,1)
        vms = vms = VertexModelSphere(locs,adjs)
        vms.gradient_descent_no_t1(phistep=0.01,thetastep=0.01)
        vms.gradient_descent_no_t1(phistep=0.001,thetastep=0.001)
        vms.gradient_descent_no_t1(phistep=0.00001,thetastep=0.00001)
        vms.gradient_descent_no_t1(phistep=0.000001,thetastep=0.000001)
        vms.save_to_file('/Users/vipul/Data/Spring2017/ab_vertex/sphere2D_r=1_p0=1_R=1_n=16/iter'+str(i)+'.pick')

In [15]:
relax_a_bunch_of_vms(10)

[array([ 0.00879331,  0.02110524,  0.99973859]), array([-0.21902446,  0.23922173,  0.94593935]), array([ -1.92194624e-04,  -3.44438523e-03,   9.99994050e-01]), array([ 0.35902498, -0.22185861,  0.90657588]), array([ 0.24499092,  0.96641443,  0.07760546]), array([-0.5191065 ,  0.85468145,  0.00693239]), array([-0.95374684, -0.29373791,  0.063914  ]), array([ 0.90489977, -0.10169196,  0.4132979 ]), array([ 0.81755702,  0.52745008, -0.23107778]), array([-0.58642293,  0.60079808, -0.54327693]), array([-0.88523134, -0.19954775, -0.42017398]), array([ 0.14297429, -0.9861998 , -0.08347638]), array([ 0.12875163,  0.05965123, -0.98988118]), array([-0.0640901 ,  0.13528775, -0.98873135]), array([-0.04023894, -0.30591113, -0.95120934]), array([ 0.09812699, -0.57775615, -0.8102894 ])]
<scipy.spatial._spherical_voronoi.SphericalVoronoi instance at 0x127873e18>
[[5, 6, 27, 24, 22], [6, 27, 26, 13, 11], [23, 24, 27, 26, 25], [21, 23, 24, 22], [0, 8, 7, 12, 11, 6, 5], [11, 13, 14, 12], [13, 14, 15, 19

energy step: -1.6437435022e-06
energy step: -1.62728821351e-06
energy step: -1.58004871764e-06
energy step: -1.55944243829e-06
energy step: -1.51715335051e-06
energy step: -1.49721253706e-06
energy step: -1.45826149378e-06
energy step: -1.44107056599e-06
energy step: -1.39375467256e-06
energy step: -1.38051672138e-06
energy step: -1.35573554871e-06
energy step: -1.32734649583e-06
energy step: -1.30547678623e-06
energy step: -1.28120345266e-06
energy step: -1.25999301304e-06
energy step: -1.23019995613e-06
energy step: -1.21931216768e-06
energy step: -1.20102819778e-06
energy step: -1.18566185847e-06
energy step: -1.18466681442e-06
energy step: -1.1571171683e-06
energy step: -1.15785655908e-06
energy step: -1.12861437174e-06
energy step: -1.12617331638e-06
energy step: -1.11126388447e-06
energy step: -1.09942374138e-06
energy step: -1.08680939093e-06
energy step: -1.07047915776e-06
energy step: -1.05913409243e-06
energy step: -1.04315878957e-06
energy step: -1.036401585e-06
energy step:

energy step: -9.01181351765e-08
energy step: -8.28764825656e-08
energy step: -8.15067267013e-08
energy step: -7.96397614522e-08
energy step: -8.15986425096e-08
energy step: -8.69163159223e-08
energy step: -7.78624382747e-08
energy step: -8.38642222334e-08
energy step: -7.65997185681e-08
energy step: -7.3927651556e-08
energy step: -7.64873675507e-08
energy step: -6.82914844674e-08
energy step: -7.52420419303e-08
energy step: -7.9935574604e-08
energy step: -7.44074100112e-08
energy step: -6.85218992658e-08
energy step: -6.15902706613e-08
energy step: -6.35352819245e-08
energy step: -7.03104205968e-08
energy step: -6.88042973707e-08
energy step: -6.7159334094e-08
energy step: -6.16214492766e-08
energy step: -6.83278358338e-08
energy step: -6.32536796275e-08
energy step: -6.90030503847e-08
energy step: -5.67652591599e-08
energy step: -5.36416564501e-08
energy step: -6.51817231301e-08
energy step: -6.13030977092e-08
energy step: -5.6325575315e-08
energy step: -5.84684016758e-08
energy step:

energy step: -0.341915469371
energy step: -0.327553884057
energy step: -0.305411383067
energy step: -0.288746432226
energy step: -0.271845042104
energy step: -0.262341481421
energy step: -0.242292979482
energy step: -0.228167099327
energy step: -0.220563059929
energy step: -0.208382754654
energy step: -0.200239607586
energy step: -0.188275361509
energy step: -0.171745066188
energy step: -0.172664906502
energy step: -0.160625915559
energy step: -0.149558545513
energy step: -0.141947758416
energy step: -0.133798471116
energy step: -0.13114009078
energy step: -0.124759156686
energy step: -0.117893148692
energy step: -0.11831980454
energy step: -0.116812196511
energy step: -0.114098858436
energy step: -0.102692107874
energy step: -0.0954124581702
energy step: -0.0989636740329
energy step: -0.087922853167
energy step: -0.0919515412972
energy step: -0.0781403521169
energy step: -0.0717576445716
energy step: -0.0711866095415
energy step: -0.0660951969497
energy step: -0.0631461254065
energy s

energy step: -3.05725222915e-07
energy step: -3.02755836401e-07
energy step: -2.86853122589e-07
energy step: -2.79299911199e-07
energy step: -2.73911354043e-07
energy step: -2.607125964e-07
energy step: -2.62134932427e-07
energy step: -2.4177492719e-07
energy step: -2.44465866217e-07
energy step: -2.38343005776e-07
energy step: -2.35051345499e-07
energy step: -2.2933986088e-07
energy step: -2.19226166109e-07
energy step: -2.08327492146e-07
energy step: -2.05738075465e-07
energy step: -2.03513906172e-07
energy step: -1.99765651132e-07
energy step: -1.89434871345e-07
energy step: -1.84839564099e-07
energy step: -1.79323819793e-07
energy step: -1.80826987162e-07
energy step: -1.85853593848e-07
energy step: -1.77376591637e-07
energy step: -1.77709637228e-07
energy step: -1.71097667589e-07
energy step: -1.68003055023e-07
energy step: -1.76060694912e-07
energy step: -1.70931400589e-07
energy step: -1.63013481824e-07
energy step: -1.67291943853e-07
energy step: -1.61153366207e-07
energy step:

energy step: -3.84021916489e-08
energy step: -4.88254272568e-08
energy step: -3.92550987272e-08
energy step: -3.96940720293e-08
energy step: -3.54597204932e-08
energy step: -4.02611419759e-08
energy step: -3.66044048405e-08
energy step: -3.27939346789e-08
energy step: -3.60442982128e-08
energy step: -3.78548463686e-08
energy step: -4.47908519163e-08
energy step: -3.29483214045e-08
energy step: -2.7615470799e-08
energy step: -3.09185850256e-08
energy step: -3.832207085e-08
energy step: -3.80990456961e-08
energy step: -3.34694618687e-08
energy step: -3.24877476032e-08
energy step: -2.87091950213e-08
energy step: -2.91443882361e-08
energy step: -3.0194428291e-08
energy step: -3.10442658247e-08
energy step: -2.81451661976e-08
energy step: -2.85075429929e-08
energy step: -3.12048200612e-08
energy step: -3.06908987113e-08
energy step: -2.50772700383e-08
energy step: -2.0660422706e-08
energy step: -2.17312390305e-08
energy step: -1.99691498892e-08
energy step: -2.69724864665e-08
energy step: 

energy step: -0.154301736484
energy step: -0.14187707148
energy step: -0.148005058457
energy step: -0.152227645155
energy step: -0.142024196468
energy step: -0.128521822257
energy step: -0.133922810859
energy step: -0.120929172737
energy step: -0.127037088385
energy step: -0.123116836751
energy step: -0.11324458259
energy step: -0.119868927012
energy step: -0.11019249277
energy step: -0.110546971074
energy step: -0.10700758882
energy step: -0.105405990763
energy step: -0.0910398901613
energy step: -0.088434663342
energy step: -0.0864684942188
energy step: -0.0735202467762
energy step: -0.0757598919307
energy step: -0.0730854645604
energy step: -0.0656494797767
energy step: -0.0634169999979
energy step: -0.0499887981096
energy step: -0.0524171538369
energy step: -0.0530305690205
energy step: -0.0465532475299
energy step: -0.0339227275151
energy step: -0.026590787617
energy step: -0.0173574155667
energy step: -0.0332609596682
energy step: -0.0252210075212
energy step: -0.0143972905307
en

energy step: -5.12706691325e-07
energy step: -5.20252228853e-07
energy step: -5.07367190039e-07
energy step: -4.99931076092e-07
energy step: -5.01883050674e-07
energy step: -4.95475802609e-07
energy step: -4.8253946261e-07
energy step: -4.74679097806e-07
energy step: -4.76278074757e-07
energy step: -4.79168676293e-07
energy step: -4.66092842544e-07
energy step: -4.70035502076e-07
energy step: -4.61730792267e-07
energy step: -4.48644300377e-07
energy step: -4.45534510618e-07
energy step: -4.41118174876e-07
energy step: -4.49032683036e-07
energy step: -4.29771887411e-07
energy step: -4.30503831694e-07
energy step: -4.2148093371e-07
energy step: -4.22977706194e-07
energy step: -4.12885810874e-07
energy step: -4.10005355889e-07
energy step: -4.07767430488e-07
energy step: -3.99691941766e-07
energy step: -3.92032831087e-07
energy step: -3.91721528104e-07
energy step: -3.90486661672e-07
energy step: -3.82443147373e-07
energy step: -3.727600415e-07
energy step: -3.72583770059e-07
energy step:

energy step: -2.35675548307
energy step: -2.05196695428
energy step: -1.81205344576
energy step: -1.62780899237
energy step: -1.44940305473
energy step: -1.2989702177
energy step: -1.18094360806
energy step: -1.08310472961
energy step: -0.987236457508
energy step: -0.901369308869
energy step: -0.844066460123
energy step: -0.793259951249
energy step: -0.730659638068
energy step: -0.683291491474
energy step: -0.639682240134
energy step: -0.581271959988
energy step: -0.544708193495
energy step: -0.508083414466
energy step: -0.46912053671
energy step: -0.429444131358
energy step: -0.403481358864
energy step: -0.378910254694
energy step: -0.337048583881
energy step: -0.315982984648
energy step: -0.277341174327
energy step: -0.253546416704
energy step: -0.22581318049
energy step: -0.213010401433
energy step: -0.200732815487
energy step: -0.192655723193
energy step: -0.168472244532
energy step: -0.162060981542
energy step: -0.150115645974
energy step: -0.146750240769
energy step: -0.127488710

energy step: -5.27394149685e-07
energy step: -5.22224098631e-07
energy step: -5.09575784235e-07
energy step: -4.99466295878e-07
energy step: -5.04003622837e-07
energy step: -4.85818418383e-07
energy step: -4.91424515303e-07
energy step: -4.61903738369e-07
energy step: -4.69079566301e-07
energy step: -4.57365501916e-07
energy step: -4.5646225999e-07
energy step: -4.50448396805e-07
energy step: -4.38489792032e-07
energy step: -4.3663956717e-07
energy step: -4.33934673083e-07
energy step: -4.12626405932e-07
energy step: -4.15520105435e-07
energy step: -4.09813168289e-07
energy step: -3.99608893531e-07
energy step: -4.05124495728e-07
energy step: -3.92704407659e-07
energy step: -3.90049706311e-07
energy step: -3.94740368392e-07
energy step: -3.79765253911e-07
energy step: -3.74256188707e-07
energy step: -3.7524401364e-07
energy step: -3.62603515214e-07
energy step: -3.5122599229e-07
energy step: -3.54298435923e-07
energy step: -3.57829122777e-07
energy step: -3.4555105799e-07
energy step: 

energy step: -2.95533179014
energy step: -2.69611681312
energy step: -2.46698212788
energy step: -2.26456972279
energy step: -2.13179268259
energy step: -2.00361051998
energy step: -1.87911074996
energy step: -1.78620168821
energy step: -1.70769429654
energy step: -1.62733550449
energy step: -1.57726756893
energy step: -1.51739312342
energy step: -1.4790420292
energy step: -1.42712139589
energy step: -1.37867334767
energy step: -1.33297137657
energy step: -1.27144534291
energy step: -1.22386905377
energy step: -1.17838696416
energy step: -1.12809776907
energy step: -1.07785597133
energy step: -1.03711586422
energy step: -0.987389479345
energy step: -0.940768117415
energy step: -0.885568500155
energy step: -0.849535110109
energy step: -0.797470716927
energy step: -0.75121917713
energy step: -0.709052160894
energy step: -0.661582089093
energy step: -0.639796113652
energy step: -0.595538777322
energy step: -0.565934737357
energy step: -0.540469923626
energy step: -0.501629630494
energy st

energy step: -1.53733026309e-06
energy step: -1.5077309854e-06
energy step: -1.48100491515e-06
energy step: -1.47719345023e-06
energy step: -1.44862286788e-06
energy step: -1.43284938758e-06
energy step: -1.41589714531e-06
energy step: -1.40212958399e-06
energy step: -1.39397465659e-06
energy step: -1.3744354419e-06
energy step: -1.35472583906e-06
energy step: -1.35123070777e-06
energy step: -1.33614290121e-06
energy step: -1.31068216547e-06
energy step: -1.29576267227e-06
energy step: -1.28921357145e-06
energy step: -1.28246378495e-06
energy step: -1.26848135551e-06
energy step: -1.24750604868e-06
energy step: -1.23110976347e-06
energy step: -1.22762145338e-06
energy step: -1.21552500332e-06
energy step: -1.19250753983e-06
energy step: -1.18805499483e-06
energy step: -1.16894742064e-06
energy step: -1.16629800573e-06
energy step: -1.14470961421e-06
energy step: -1.13195841323e-06
energy step: -1.12340111968e-06
energy step: -1.11199253183e-06
energy step: -1.09407071136e-06
energy ste

energy step: -1.30736026449e-07
energy step: -1.27970338326e-07
energy step: -1.25702200648e-07
energy step: -1.28582740899e-07
energy step: -1.25673352613e-07
energy step: -1.22918521583e-07
energy step: -1.30943391241e-07
energy step: -1.20439665352e-07
energy step: -1.17740711403e-07
energy step: -1.30705132051e-07
energy step: -1.28498271579e-07
energy step: -1.20520184055e-07
energy step: -1.10741837034e-07
energy step: -1.20787660762e-07
energy step: -1.18471859878e-07
energy step: -1.19300011647e-07
energy step: -1.17541134159e-07
energy step: -1.22719256979e-07
energy step: -1.17590730042e-07
energy step: -1.06253850163e-07
energy step: -1.11590537699e-07
energy step: -1.14102789439e-07
energy step: -1.28134956867e-07
energy step: -1.08243256136e-07
energy step: -1.10070658366e-07
energy step: -1.19206987392e-07
energy step: -1.16883001056e-07
energy step: -1.10558204369e-07
energy step: -1.21356634963e-07
energy step: -1.0899483982e-07
energy step: -1.24488678921e-07
energy st

energy step: -6.14197688265e-08
energy step: -7.06761511537e-08
energy step: -7.21687172245e-08
energy step: -6.06696630712e-08
energy step: -6.23646485565e-08
energy step: -7.47625108488e-08
energy step: -7.0322045076e-08
energy step: -6.53147367302e-08
energy step: -5.90805200318e-08
energy step: -5.92951607814e-08
energy step: -7.36749825592e-08
energy step: -7.58065823447e-08
energy step: -7.24018320852e-08
energy step: -6.97311008935e-08
energy step: -6.24456504283e-08
energy step: -6.24018809958e-08
energy step: -7.04643241534e-08
energy step: -6.89568651069e-08
energy step: -6.70785027523e-08
energy step: -6.33204990663e-08
energy step: -6.06171113304e-08
energy step: -6.57374528146e-08
energy step: -7.36701792903e-08
energy step: -7.46944976981e-08
energy step: -6.81835956584e-08
energy step: -5.86217367982e-08
energy step: -5.80585322041e-08
energy step: -6.52754579278e-08
energy step: -5.70167060232e-08
energy step: -6.24432061613e-08
energy step: -6.40565929189e-08
energy st

energy step: -2.05659773655e-08
energy step: -2.10402504308e-08
energy step: -1.94720541913e-08
energy step: -1.91324147636e-08
energy step: -1.95424831873e-08
energy step: -2.71505200544e-08
energy step: -1.94934557385e-08
energy step: -1.90555056179e-08
energy step: -2.21821778723e-08
energy step: -1.99454746053e-08
energy step: -1.95862810415e-08
energy step: -1.82453732123e-08
energy step: -1.95420000182e-08
energy step: -1.79922494681e-08
energy step: -1.9505733917e-08
energy step: -2.26134204695e-08
energy step: -2.21687628255e-08
energy step: -2.17701767724e-08
energy step: -1.8747186914e-08
energy step: -1.84172392892e-08
energy step: -1.71872045485e-08
energy step: -1.68475935425e-08
energy step: -1.96883149783e-08
energy step: -1.69451084275e-08
energy step: -2.13799182802e-08
energy step: -1.93068672161e-08
energy step: -1.6796974478e-08
energy step: -1.6457363472e-08
energy step: -1.61177808877e-08
energy step: -1.64563402905e-08
energy step: -1.57521924393e-08
energy step:

energy step: -3.98244992539e-10
energy step: -3.46943807017e-10
energy step: -1.79369408215e-10
energy step: -1.86958004633e-10
energy step: -1.20877530208e-10
energy step: -8.3730355982e-11
energy step: -6.52562448522e-11
energy step: -3.61808361049e-11
energy step: -3.54134499503e-11
energy step: -7.19069248589e-11
energy step: -5.35465005669e-11
energy step: -2.98996383208e-11
energy step: -4.6952663979e-11
energy step: -2.56648036157e-11
energy step: -4.14104306401e-11
energy step: -2.21120899369e-11
energy step: -2.50395260082e-11
energy step: -7.62554464018e-11
energy step: -4.30304680776e-11
energy step: -1.84456894203e-11
energy step: -3.21165316564e-11
energy step: -3.04396508e-11
energy step: -1.60866875376e-11
energy step: -1.27045041154e-11
energy step: -1.18518528325e-11
energy step: -7.41806616134e-12
energy step: -3.9221959014e-12
energy step: -3.52429196937e-12
energy step: -2.52100562648e-11
energy step: -1.11413100967e-11
energy step: -5.68434188608e-12
energy step: -

energy step: -3.35648297778e-06
energy step: -3.2730676196e-06
energy step: -3.20097021245e-06
energy step: -3.15208356483e-06
energy step: -3.10058163677e-06
energy step: -3.0481616875e-06
energy step: -2.991197249e-06
energy step: -2.94305036164e-06
energy step: -2.89762428451e-06
energy step: -2.85504853537e-06
energy step: -2.81164633975e-06
energy step: -2.75003930028e-06
energy step: -2.71818984743e-06
energy step: -2.67301984991e-06
energy step: -2.63032171688e-06
energy step: -2.58591435909e-06
energy step: -2.54485988194e-06
energy step: -2.50356072229e-06
energy step: -2.45959697054e-06
energy step: -2.42298381181e-06
energy step: -2.38026441934e-06
energy step: -2.33485806689e-06
energy step: -2.29746095215e-06
energy step: -2.2667587416e-06
energy step: -2.23553374212e-06
energy step: -2.19227572984e-06
energy step: -2.15646232959e-06
energy step: -2.10963776226e-06
energy step: -2.08483425013e-06
energy step: -2.05077839155e-06
energy step: -2.00828884545e-06
energy step: 

energy step: -1.58486102464e-07
energy step: -1.55101133714e-07
energy step: -1.46974116433e-07
energy step: -1.59285718837e-07
energy step: -1.61308093993e-07
energy step: -1.48031915614e-07
energy step: -1.33845901473e-07
energy step: -1.41152440847e-07
energy step: -1.5441838741e-07
energy step: -1.5286082089e-07
energy step: -1.45132304397e-07
energy step: -1.39694293466e-07
energy step: -1.35839087534e-07
energy step: -1.35371067245e-07
energy step: -1.42180738294e-07
energy step: -1.33766121735e-07
energy step: -1.32795264562e-07
energy step: -1.29031690221e-07
energy step: -1.36483095048e-07
energy step: -1.28203197391e-07
energy step: -1.23733912005e-07
energy step: -1.3369006524e-07
energy step: -1.14767573223e-07
energy step: -1.14084656389e-07
energy step: -1.24226858134e-07
energy step: -1.10983080504e-07
energy step: -1.08739243387e-07
energy step: -1.13759313081e-07
energy step: -1.22621031551e-07
energy step: -1.04800506051e-07
energy step: -1.02911769773e-07
energy step

energy step: -0.423255152941
energy step: -0.420791684021
energy step: -0.361205549986
energy step: -0.35038878765
energy step: -0.322472457524
energy step: -0.301881859259
energy step: -0.289516164806
energy step: -0.268316446171
energy step: -0.242158003247
energy step: -0.226289949654
energy step: -0.205664454065
energy step: -0.185256937105
energy step: -0.18463695567
energy step: -0.161629364892
energy step: -0.134458701721
energy step: -0.139256423796
energy step: -0.132776807962
energy step: -0.115449015983
energy step: -0.111107909369
energy step: -0.108310544678
energy step: -0.0985113776967
energy step: -0.102308055864
energy step: -0.0871504026302
energy step: -0.082816133425
energy step: -0.0820126647595
energy step: -0.0738417005592
energy step: -0.0733701242517
energy step: -0.058532897054
energy step: -0.0496849007598
energy step: -0.0483126171964
energy step: -0.049227911384
energy step: -0.0346684323402
energy step: -0.028211389659
energy step: -0.0256176820302
energy 

energy step: -1.26330823491e-06
energy step: -1.24656298794e-06
energy step: -1.22398421354e-06
energy step: -1.21871141801e-06
energy step: -1.19674027133e-06
energy step: -1.17393037158e-06
energy step: -1.1647392455e-06
energy step: -1.15343826224e-06
energy step: -1.12887761361e-06
energy step: -1.11413601189e-06
energy step: -1.10134044462e-06
energy step: -1.08370747398e-06
energy step: -1.06753944351e-06
energy step: -1.05909413151e-06
energy step: -1.04976868442e-06
energy step: -1.03576809352e-06
energy step: -1.02643488731e-06
energy step: -1.01548596376e-06
energy step: -1.00676737702e-06
energy step: -9.98116547635e-07
energy step: -9.87642721384e-07
energy step: -9.74676169108e-07
energy step: -9.62585744446e-07
energy step: -9.59456173177e-07
energy step: -9.44853240981e-07
energy step: -9.22657534375e-07
energy step: -9.35082113074e-07
energy step: -9.06601059114e-07
energy step: -9.04166427063e-07
energy step: -8.98426463891e-07
energy step: -8.89576682539e-07
energy st

energy step: -1.05081369384e-07
energy step: -9.37949380386e-08
energy step: -9.81617631624e-08
energy step: -9.85989743185e-08
energy step: -8.81615562776e-08
energy step: -8.7519367753e-08
energy step: -8.13502651908e-08
energy step: -9.08539732336e-08
energy step: -8.5410306383e-08
energy step: -9.87807311503e-08
energy step: -9.75353486865e-08
energy step: -8.12176494946e-08
energy step: -8.82170354544e-08
energy step: -9.49203808887e-08
energy step: -8.80350228272e-08
energy step: -8.55851851611e-08
energy step: -9.79382264177e-08
energy step: -7.8266964465e-08
energy step: -8.6581138703e-08
energy step: -7.96955532678e-08
energy step: -8.78257253589e-08
energy step: -7.30664453386e-08
energy step: -8.68592451297e-08
energy step: -9.07279797957e-08
energy step: -7.67944072777e-08
energy step: -7.42805355003e-08
energy step: -9.45562419474e-08
energy step: -9.85507710993e-08
energy step: -9.10453650249e-08
energy step: -8.51884465192e-08
energy step: -8.54496704505e-08
energy step:

energy step: -4.70834038424e-10
energy step: -4.62875959784e-10
energy step: -4.54832616015e-10
energy step: -4.46789272246e-10
energy step: -4.38802771896e-10
energy step: -4.30731006418e-10
energy step: -5.49562173546e-10
energy step: -5.58742385692e-10
energy step: -4.09045242122e-10
energy step: -4.00973476644e-10
energy step: -3.92986976294e-10
energy step: -3.84943632525e-10
energy step: -4.11631617681e-10
energy step: -7.9486994764e-10
energy step: -4.07453626394e-10
energy step: -3.99438704335e-10
energy step: -3.91395360566e-10
energy step: -3.83352016797e-10
energy step: -3.75393938157e-10
energy step: -3.67293750969e-10
energy step: -3.59307250619e-10
energy step: -5.15882447871e-10
energy step: -3.85085741073e-10
energy step: -3.77042397304e-10
energy step: -3.69055896954e-10
energy step: -3.61040974894e-10
energy step: -3.52969209416e-10
energy step: -3.44982709066e-10
energy step: -3.36967787007e-10
energy step: -3.51320750269e-10
energy step: -3.62433638657e-10
energy st

energy step: -3.32534000336e-12
energy step: -3.24007487507e-12
energy step: -3.18323145621e-12
energy step: -3.06954461848e-12
energy step: -2.98427949019e-12
energy step: -2.92743607133e-12
energy step: -2.84217094304e-12
energy step: -2.75690581475e-12
energy step: -4.49063009e-12
energy step: -2.98427949019e-12
energy step: -2.95585778076e-12
energy step: -2.84217094304e-12
energy step: -2.78532752418e-12
energy step: -2.70006239589e-12
energy step: -2.6147972676e-12
energy step: -2.55795384874e-12
energy step: -2.41584530158e-12
energy step: -2.41584530158e-12
energy step: -2.27373675443e-12
energy step: -2.21689333557e-12
energy step: -2.13162820728e-12
energy step: -2.04636307899e-12
energy step: -2.245315045e-12
energy step: -4.51905179943e-12
energy step: -1.95825577975e-11
energy step: -2.44426701101e-12
energy step: -2.27373675443e-12
energy step: -2.245315045e-12
energy step: -2.10320649785e-12
energy step: -2.04636307899e-12
energy step: -1.98951966013e-12
energy step: -1.

energy step: -1.03125079249e-05
energy step: -7.29396634824e-06
energy step: -1.24076066754e-05
energy step: -4.57010095261e-05
energy step: -3.76715867674e-05
energy step: -6.33747239931e-06
energy step: -1.59148473529e-05
energy step: -1.21359596505e-05
energy step: -5.89576697507e-06
energy step: -1.30082826786e-05
energy step: -1.2580158625e-05
energy step: 0.0
done
energy step: -4.72366642157e-06
energy step: -4.49303448136e-06
energy step: -4.27292610539e-06
energy step: -4.08053796264e-06
energy step: -3.89039067272e-06
energy step: -3.71177867464e-06
energy step: -3.54479558951e-06
energy step: -3.38328575822e-06
energy step: -3.23340097452e-06
energy step: -3.08581911668e-06
energy step: -2.95382093896e-06
energy step: -2.81206055774e-06
energy step: -2.68437960926e-06
energy step: -2.56987235048e-06
energy step: -2.47590065783e-06
energy step: -2.37472468712e-06
energy step: -2.30124379641e-06
energy step: -2.24224689305e-06
energy step: -2.17570399741e-06
energy step: -2.118

energy step: -5.37096696007e-08
energy step: -5.22847471984e-08
energy step: -4.39708003341e-08
energy step: -4.84841962134e-08
energy step: -4.61546676433e-08
energy step: -5.46731939721e-08
energy step: -4.36714344687e-08
energy step: -3.95444885726e-08
energy step: -4.38133440639e-08
energy step: -3.9157299625e-08
energy step: -3.31388321229e-08
energy step: -4.28523492246e-08
energy step: -4.01545889872e-08
energy step: -3.05979312998e-08
energy step: -4.58319107111e-08
energy step: -4.32940510109e-08
energy step: -3.16185833071e-08
energy step: -3.87466343454e-08
energy step: -3.18139825595e-08
energy step: -3.56736222784e-08
energy step: -2.67065445314e-08
energy step: -3.00526608044e-08
energy step: -3.4820828887e-08
energy step: -2.511271191e-08
energy step: -2.59288981397e-08
energy step: -1.87801276752e-08
energy step: -1.92861193682e-08
energy step: -2.59913406353e-08
energy step: -2.72622457942e-08
energy step: -1.75139405201e-08
energy step: -2.22379981096e-08
energy step:

energy step: -0.0127996621695
energy step: -0.0164535262543
energy step: -0.0154357120767
energy step: -0.0207758749914
energy step: -0.0120695185094
energy step: -0.0201016716979
energy step: -0.0179138384399
energy step: -0.0133222729779
energy step: -0.0132520505243
energy step: -0.0128734072744
energy step: -0.00801601696762
energy step: -0.00877509527137
energy step: -0.017399593392
energy step: -0.010617187569
energy step: -0.0129500700794
energy step: -0.0129233458087
energy step: -0.0101855127169
energy step: -0.0108557908417
energy step: -0.00792641389532
energy step: -0.0108642099251
energy step: -0.0122173895631
energy step: -0.00596182415609
energy step: -0.00779857911365
energy step: -0.00874626811515
energy step: -0.00838326018871
energy step: -0.00990465771778
energy step: -0.00509943257268
energy step: -0.00642581140465
energy step: -0.00932841929699
energy step: -0.00471456513137
energy step: -0.00363004306496
energy step: -0.00803746217346
energy step: -0.002962622324

energy step: -2.38140870579e-07
energy step: -2.28451568773e-07
energy step: -2.29015171271e-07
energy step: -2.18165951082e-07
energy step: -2.25388646413e-07
energy step: -2.20072308821e-07
energy step: -2.22920959914e-07
energy step: -2.23960341827e-07
energy step: -2.1899506919e-07
energy step: -2.1805701067e-07
energy step: -2.16360149352e-07
energy step: -2.08763594856e-07
energy step: -1.97423986492e-07
energy step: -2.01784445153e-07
energy step: -2.0830711378e-07
energy step: -2.02038819452e-07
energy step: -1.98447935418e-07
energy step: -2.06100168043e-07
energy step: -2.09609652302e-07
energy step: -2.00629671099e-07
energy step: -1.87294119769e-07
energy step: -1.95453139895e-07
energy step: -1.87864202417e-07
energy step: -1.92008855038e-07
energy step: -1.96057101221e-07
energy step: -1.81695838819e-07
energy step: -1.92714765035e-07
energy step: -1.83286488209e-07
energy step: -1.89671396811e-07
energy step: -1.81155229484e-07
energy step: -1.78580847887e-07
energy step

energy step: -3.05154310766
energy step: -2.75540851311
energy step: -2.55286320579
energy step: -2.38460108702
energy step: -2.2051695323
energy step: -2.0736936495
energy step: -1.93256824549
energy step: -1.79601128605
energy step: -1.6767843881
energy step: -1.55509643567
energy step: -1.44514574771
energy step: -1.33733535878
energy step: -1.22547578575
energy step: -1.14121914998
energy step: -1.04482000674
energy step: -0.946945537665
energy step: -0.884818471481
energy step: -0.811691688054
energy step: -0.741934406761
energy step: -0.684473403525
energy step: -0.636129021779
energy step: -0.573377373027
energy step: -0.542054913722
energy step: -0.497543172202
energy step: -0.45410971277
energy step: -0.399928213608
energy step: -0.386076599824
energy step: -0.343790329319
energy step: -0.311713097145
energy step: -0.28870145851
energy step: -0.264009197559
energy step: -0.242295295101
energy step: -0.216734721914
energy step: -0.210167404002
energy step: -0.191118107863
energ

energy step: -5.00205146636e-07
energy step: -4.98509052704e-07
energy step: -4.7646301482e-07
energy step: -4.81954771203e-07
energy step: -4.66995459192e-07
energy step: -4.7116799351e-07
energy step: -4.59697162114e-07
energy step: -4.49810670489e-07
energy step: -4.41522274741e-07
energy step: -4.31607816154e-07
energy step: -4.19569914811e-07
energy step: -4.1227588099e-07
energy step: -4.09550580116e-07
energy step: -4.14983389874e-07
energy step: -4.18658146373e-07
energy step: -4.03920637382e-07
energy step: -3.89204046769e-07
energy step: -3.90893433178e-07
energy step: -3.82967073165e-07
energy step: -3.65629546195e-07
energy step: -3.76058437723e-07
energy step: -3.73206205495e-07
energy step: -3.60339186045e-07
energy step: -3.61410457117e-07
energy step: -3.53924349383e-07
energy step: -3.48531784766e-07
energy step: -3.35339791491e-07
energy step: -3.27741872752e-07
energy step: -3.49541323885e-07
energy step: -3.38789789112e-07
energy step: -3.21582035667e-07
energy step

energy step: -5.84693680139e-08
energy step: -5.7024749367e-08
energy step: -5.80880623602e-08
energy step: -5.58351302971e-08
energy step: -5.49409833184e-08
energy step: -5.71815803596e-08
energy step: -5.78387471251e-08
energy step: -5.80357095714e-08
energy step: -5.91089701629e-08
energy step: -5.62265540793e-08
energy step: -5.49426317775e-08
energy step: -5.38935864824e-08
energy step: -5.42205498277e-08
energy step: -5.75603849029e-08
energy step: -5.44586100659e-08
energy step: -5.36425091013e-08
energy step: -5.24618712916e-08
energy step: -5.26647454535e-08
energy step: -5.65187292523e-08
energy step: -5.68389282307e-08
energy step: -6.0714967276e-08
energy step: -5.2867562772e-08
energy step: -5.44870317754e-08
energy step: -5.22355207977e-08
energy step: -5.51196421839e-08
energy step: -5.13396685164e-08
energy step: -5.37300479664e-08
energy step: -5.36349489266e-08
energy step: -5.77547893954e-08
energy step: -5.55013457415e-08
energy step: -5.28638111064e-08
energy step

energy step: -1.91841422748e-08
energy step: -1.83328552339e-08
energy step: -2.04968841899e-08
energy step: -1.69180225384e-08
energy step: -1.77415131475e-08
energy step: -1.90921127796e-08
energy step: -1.61047637448e-08
energy step: -1.61595039572e-08
energy step: -1.54556119014e-08
energy step: -1.82882331501e-08
energy step: -1.57260160449e-08
energy step: -1.53717110152e-08
energy step: -1.55440602612e-08
energy step: -1.52266466102e-08
energy step: -1.73704393092e-08
energy step: -1.5142745724e-08
energy step: -1.46177967508e-08
energy step: -1.42383100865e-08
energy step: -1.37799816002e-08
energy step: -1.33299522531e-08
energy step: -1.3483429484e-08
energy step: -1.49626657731e-08
energy step: -1.6164904082e-08
energy step: -2.62444359578e-08
energy step: -2.04216235034e-08
energy step: -1.60974877872e-08
energy step: -1.34815536512e-08
energy step: -1.65227334037e-08
energy step: -1.30326611725e-08
energy step: -1.37610527418e-08
energy step: -1.33603634822e-08
energy step

energy step: -5.66160451854e-11
energy step: -9.0267349151e-11
energy step: -6.66773303237e-11
energy step: -4.46220838057e-11
energy step: -5.45696821064e-11
energy step: -2.17141860048e-11
energy step: -2.52953213931e-11
energy step: -1.61435309565e-11
energy step: -1.60866875376e-11
energy step: -1.13118403533e-11
energy step: -1.06865627458e-11
energy step: -1.00044417195e-11
energy step: -1.11413100967e-11
energy step: -9.77706804406e-12
energy step: -9.20863385545e-12
energy step: -8.58335624798e-12
energy step: -9.77706804406e-12
energy step: -2.01225702767e-11
energy step: -2.39310793404e-11
energy step: -3.0638602766e-11
energy step: -1.04591890704e-11
energy step: -9.54969436862e-12
energy step: -8.92441676115e-12
energy step: -8.29913915368e-12
energy step: -7.73070496507e-12
energy step: -6.99174051988e-12
energy step: -6.42330633127e-12
energy step: -5.7980287238e-12
energy step: -5.17275111633e-12
energy step: -8.64019966684e-12
energy step: -1.73940861714e-11
energy step

In [10]:
import pickle
def save_to_file(self, filename):
    #pickle v, adjs, radius, p0, and r.
    #importantly, we're not pickling the actual VertexModel instance so that I can change object methods without messing everything up

    with open(filename,'wb') as pickle_file:
        data = {'locs':self.v, 'adjs':self.adj, 'radius':self.radius, 'p0':self.p0, 'r':self.r}
        pickle.dump(data, pickle_file)

In [24]:
save_to_file(vm2,'/Users/vipul/Data/cyst_images/test_folder/test_pickle.pick')

IOError: [Errno 2] No such file or directory: '/Users/vipul/Data/cyst_images/test_folder/test_pickle.pick'

In [8]:
def load_from_file(filename):
    with open(filename,'rb') as pickle_file:
        data = pickle.load(pickle_file)
    vm = VertexModelSphere(data['locs'],data['adjs'],radius=data['radius'],p0=data['p0'], r=data['r'])
    return vm

In [3]:
vm2 = VertexModelSphere.load_from_file('/Users/vipul/Data/Spring2017/ab_vertex/sphere2D_r=1_p0=1_R=1_n=16/iter8.pick')

In [4]:
vm2.draw_model()

In [11]:
lox = vms.v_cart

In [15]:
sv = SphericalVoronoi(np.array(lox),radius=1)

In [17]:
type(sv.regions[0])

list

In [19]:
sv.sort_vertices_of_regions()

In [20]:
sv.regions

[[1, 6, 7, 5, 4],
 [0, 5, 7],
 [0, 2, 6, 7],
 [1, 6, 2, 3],
 [1, 4, 3],
 [0, 2, 3, 4, 5]]

In [4]:
locs

[array([ 1.43195343, -1.27906306]),
 array([ 1.71595745, -2.77328099]),
 array([ 1.84476368, -2.39257612]),
 array([ 1.65555163, -1.0094838 ]),
 array([ 0.88202571,  0.15043531]),
 array([ 1.46196468,  1.70589956]),
 array([ 1.29324436,  1.76565432]),
 array([ 1.70004872, -2.77879701]),
 array([ 0.58201078, -0.07893285]),
 array([ 0.88197941, -1.35661025]),
 array([ 2.61222727, -1.53329633]),
 array([ 2.56405702, -1.22423327]),
 array([ 1.80567128,  0.71583848]),
 array([ 2.6557683 , -0.23396772]),
 array([ 1.6353715 ,  0.00375844]),
 array([ 1.59612448,  0.07419555]),
 array([ 0.30610149,  0.31079523]),
 array([ 1.05180214,  2.00231078]),
 array([ 1.02145727,  2.08744535]),
 array([ 2.3867941 ,  2.59270997]),
 array([ 2.87831909, -2.52384043]),
 array([ 2.34810023,  2.26872443]),
 array([ 2.67280443,  0.92595477]),
 array([ 2.74506389,  0.582548  ]),
 array([ 0.50778292,  2.96960871]),
 array([ 0.18127111,  0.28211069]),
 array([ 0.68826191, -2.42030928]),
 array([ 0.67244044, -2.3531

In [5]:
adjs

[[9, 2, 3],
 [2, 19, 7],
 [0, 1, 10],
 [0, 11, 14],
 [8, 6, 15],
 [12, 21, 6],
 [17, 4, 5],
 [1, 18, 26],
 [16, 9, 4],
 [8, 0, 27],
 [2, 11, 20],
 [10, 3, 13],
 [5, 22, 15],
 [11, 14, 23],
 [3, 13, 15],
 [12, 4, 14],
 [8, 17, 25],
 [16, 18, 6],
 [24, 17, 7],
 [1, 20, 21],
 [10, 19, 23],
 [19, 5, 22],
 [12, 21, 23],
 [20, 13, 22],
 [25, 18, 26],
 [16, 24, 27],
 [24, 27, 7],
 [25, 26, 9]]

In [10]:
vms.faceareas

[1.2115657123894401,
 1.1472470608108978,
 0.89481292505095311,
 0.86255081459596639,
 1.4376138615617613,
 0.81486333579893255,
 0.68154569558279832,
 1.0917413861465484,
 1.0183692863714064,
 0.90733632383177465,
 0.51265045251465224,
 0.29074942082039534,
 0.6767549093995342,
 0.40546086437442241,
 0.40863215684262855,
 0.20447640826706781]